-- MySQL Script generated by MySQL Workbench
-- Thu Sep 25 21:25:36 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema mi_base_datos
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mi_base_datos` ;

-- -----------------------------------------------------
-- Schema mi_base_datos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mi_base_datos` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `mi_base_datos` ;

-- -----------------------------------------------------
-- Table `mi_base_datos`.`tipos_inmuebles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mi_base_datos`.`tipos_inmuebles` ;

CREATE TABLE IF NOT EXISTS `mi_base_datos`.`tipos_inmuebles` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `mi_base_datos`.`personas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mi_base_datos`.`personas` ;

CREATE TABLE IF NOT EXISTS `mi_base_datos`.`personas` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(100) NOT NULL,
  `Apellido` VARCHAR(100) NOT NULL,
  `DNI` VARCHAR(20) NOT NULL,
  `Email` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 48
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE UNIQUE INDEX `DNI` ON `mi_base_datos`.`personas` (`DNI` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mi_base_datos`.`inmuebles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mi_base_datos`.`inmuebles` ;

CREATE TABLE IF NOT EXISTS `mi_base_datos`.`inmuebles` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Direccion` VARCHAR(255) NOT NULL,
  `Tipo` VARCHAR(50) NOT NULL,
  `MetrosCuadrados` INT NOT NULL,
  `Precio` DECIMAL(10,2) NOT NULL,
  `PropietarioID` INT NOT NULL,
  `Activo` TINYINT(1) NOT NULL DEFAULT '1',
  `TipoId` INT NULL DEFAULT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `fk_inmuebles_tipo`
    FOREIGN KEY (`TipoId`)
    REFERENCES `mi_base_datos`.`tipos_inmuebles` (`Id`),
  CONSTRAINT `inmuebles_ibfk_1`
    FOREIGN KEY (`PropietarioID`)
    REFERENCES `mi_base_datos`.`personas` (`ID`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 48
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `inmuebles_ibfk_1` ON `mi_base_datos`.`inmuebles` (`PropietarioID` ASC) VISIBLE;

CREATE INDEX `fk_inmuebles_tipo` ON `mi_base_datos`.`inmuebles` (`TipoId` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mi_base_datos`.`contratos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mi_base_datos`.`contratos` ;

CREATE TABLE IF NOT EXISTS `mi_base_datos`.`contratos` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `InquilinoID` INT NOT NULL,
  `InmuebleID` INT NOT NULL,
  `FechaInicio` DATE NOT NULL,
  `FechaFin` DATE NOT NULL,
  `MontoMensual` DECIMAL(10,2) NOT NULL,
  `Estado` VARCHAR(50) NULL DEFAULT 'Vigente',
  `CreadoPor` INT NOT NULL,
  `TerminadoPor` INT NULL DEFAULT NULL,
  PRIMARY KEY (`Id`),
  CONSTRAINT `fk_contrato_inmueble`
    FOREIGN KEY (`InmuebleID`)
    REFERENCES `mi_base_datos`.`inmuebles` (`ID`)
    ON DELETE CASCADE,
  CONSTRAINT `fk_contrato_inquilino`
    FOREIGN KEY (`InquilinoID`)
    REFERENCES `mi_base_datos`.`personas` (`ID`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 24
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `fk_contrato_inquilino` ON `mi_base_datos`.`contratos` (`InquilinoID` ASC) VISIBLE;

CREATE INDEX `fk_contrato_inmueble` ON `mi_base_datos`.`contratos` (`InmuebleID` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mi_base_datos`.`usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mi_base_datos`.`usuarios` ;

CREATE TABLE IF NOT EXISTS `mi_base_datos`.`usuarios` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Email` VARCHAR(255) NOT NULL,
  `PasswordHash` VARCHAR(255) NOT NULL,
  `Nombre` VARCHAR(100) NOT NULL,
  `Apellido` VARCHAR(100) NOT NULL,
  `Rol` VARCHAR(50) NOT NULL,
  `AvatarUrl` VARCHAR(255) NULL DEFAULT '/avatars/default.png',
  PRIMARY KEY (`Id`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE UNIQUE INDEX `Email` ON `mi_base_datos`.`usuarios` (`Email` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mi_base_datos`.`pagos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mi_base_datos`.`pagos` ;

CREATE TABLE IF NOT EXISTS `mi_base_datos`.`pagos` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `ContratoId` INT NOT NULL,
  `FechaPago` DATE NOT NULL,
  `Detalle` VARCHAR(255) NULL DEFAULT NULL,
  `Importe` DECIMAL(15,2) NOT NULL,
  `CreadoPor` INT NOT NULL,
  `AnuladoPor` INT NULL DEFAULT NULL,
  PRIMARY KEY (`Id`),
  CONSTRAINT `fk_pagos_anulado`
    FOREIGN KEY (`AnuladoPor`)
    REFERENCES `mi_base_datos`.`usuarios` (`Id`),
  CONSTRAINT `fk_pagos_creado`
    FOREIGN KEY (`CreadoPor`)
    REFERENCES `mi_base_datos`.`usuarios` (`Id`),
  CONSTRAINT `pagos_ibfk_1`
    FOREIGN KEY (`ContratoId`)
    REFERENCES `mi_base_datos`.`contratos` (`Id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `ContratoId` ON `mi_base_datos`.`pagos` (`ContratoId` ASC) VISIBLE;

CREATE INDEX `fk_pagos_creado` ON `mi_base_datos`.`pagos` (`CreadoPor` ASC) VISIBLE;

CREATE INDEX `fk_pagos_anulado` ON `mi_base_datos`.`pagos` (`AnuladoPor` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mi_base_datos`.`roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mi_base_datos`.`roles` ;

CREATE TABLE IF NOT EXISTS `mi_base_datos`.`roles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE UNIQUE INDEX `nombre` ON `mi_base_datos`.`roles` (`nombre` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mi_base_datos`.`persona_roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mi_base_datos`.`persona_roles` ;

CREATE TABLE IF NOT EXISTS `mi_base_datos`.`persona_roles` (
  `persona_id` INT NOT NULL,
  `rol_id` INT NOT NULL,
  PRIMARY KEY (`persona_id`, `rol_id`),
  CONSTRAINT `persona_roles_ibfk_1`
    FOREIGN KEY (`persona_id`)
    REFERENCES `mi_base_datos`.`personas` (`ID`)
    ON DELETE CASCADE,
  CONSTRAINT `persona_roles_ibfk_2`
    FOREIGN KEY (`rol_id`)
    REFERENCES `mi_base_datos`.`roles` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `rol_id` ON `mi_base_datos`.`persona_roles` (`rol_id` ASC) VISIBLE;

USE `mi_base_datos`;

DELIMITER $$

USE `mi_base_datos`$$
DROP TRIGGER IF EXISTS `mi_base_datos`.`trg_contrato_no_duplicado` $$
USE `mi_base_datos`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `mi_base_datos`.`trg_contrato_no_duplicado`
BEFORE INSERT ON `mi_base_datos`.`contratos`
FOR EACH ROW
BEGIN
    DECLARE existe INT;

    SELECT COUNT(*) INTO existe
    FROM contratos
    WHERE InmuebleID = NEW.InmuebleID
      AND Estado = 'Vigente'
      AND (
            (NEW.FechaInicio BETWEEN FechaInicio AND FechaFin) OR
            (NEW.FechaFin BETWEEN FechaInicio AND FechaFin) OR
            (FechaInicio BETWEEN NEW.FechaInicio AND NEW.FechaFin)
          );

    IF existe > 0 THEN
        SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = '❌ Este inmueble ya tiene un contrato vigente en las fechas indicadas.';
    END IF;
END$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
