-- MySQL Script generated by MySQL Workbench
-- Fri Aug 22 15:40:17 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema mi_base_datos
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mi_base_datos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mi_base_datos` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `mi_base_datos` ;

-- -----------------------------------------------------
-- Table `mi_base_datos`.`personas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mi_base_datos`.`personas` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(100) NOT NULL,
  `Apellido` VARCHAR(100) NOT NULL,
  `Tipo` ENUM('Inquilino', 'Propietario') NOT NULL,
  `DNI` VARCHAR(20) NOT NULL,
  `Email` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `DNI` (`DNI` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 21
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `mi_base_datos`.`inmuebles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mi_base_datos`.`inmuebles` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Direccion` VARCHAR(255) NOT NULL,
  `Tipo` VARCHAR(50) NOT NULL,
  `MetrosCuadrados` INT NOT NULL,
  `Precio` DECIMAL(10,2) NOT NULL,
  `PropietarioID` INT NOT NULL,
  `Activo` TINYINT(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`ID`),
  INDEX `PropietarioID` (`PropietarioID` ASC) VISIBLE,
  CONSTRAINT `inmuebles_ibfk_1`
    FOREIGN KEY (`PropietarioID`)
    REFERENCES `mi_base_datos`.`personas` (`ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 35
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `mi_base_datos`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mi_base_datos`.`usuarios` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Email` VARCHAR(255) NOT NULL,
  `PasswordHash` VARCHAR(255) NOT NULL,
  `Nombre` VARCHAR(100) NOT NULL,
  `Apellido` VARCHAR(100) NOT NULL,
  `Rol` VARCHAR(50) NOT NULL,
  `AvatarUrl` VARCHAR(255) NULL DEFAULT '/avatars/default.png',
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `Email` (`Email` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
